fun MathAbs (value){
    if (value < 0) return -value;
    return value;
    }

fun MathMin (value_a, value_b){
    if (value_a < value_b) return value_a;
    return value_b;
    }

fun MathMax (value_a, value_b){
    if (value_a > value_b) return value_a;
    return value_b;
    }

fun MathClamp (value, min, max){
    if (value < min) return min;
    if (value > max) return max;
    return value;
    }


MathPi = 3.14159265358979323846;
