#!/bin/sh

set -e

DEB_HOST_MULTIARCH="$(dpkg-architecture -qDEB_HOST_MULTIARCH)"

cat << EOF
bin
etc/plymouth
lib/${DEB_HOST_MULTIARCH}/*.so.*
sbin
usr/lib/${DEB_HOST_MULTIARCH}/libply-boot-client.so.*
usr/lib/${DEB_HOST_MULTIARCH}/plymouth/details.so
usr/lib/${DEB_HOST_MULTIARCH}/plymouth/text.so
usr/lib/${DEB_HOST_MULTIARCH}/plymouth/*-initrd
usr/sbin
usr/share/man/man8/plymouth.8
usr/share/plymouth/plymouthd.defaults
usr/share/plymouth/themes/text
usr/share/plymouth/themes/details
EOF
