#!/bin/sh

set -e

case "${1}" in
	configure)
		case "$(plymouth-set-default-theme || true)" in
			.plymouth|"")
				plymouth-set-default-theme text
				;;
		esac

		if [ -x /usr/sbin/update-initramfs ]
		then
			update-initramfs -u
		fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
